const booksData = [
  {
    id: "breast-cancer",
    title: "Pink Ribbon",
    description: "Be stronger with you.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/BreastCancer.png`,
    tags: ["Strength", "Hope", "Faith"],
    x: 50,
    y: 50,
    price: 280,
    special: "",
    brightness: 0.8,
  },
  {
    id: "child-of-god",
    title: "Child Of God",
    description: "Embracing your inner strength.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/ChildOfGod.png`,
    tags: ["Faith", "Strength", "Hope"],
    price: 180,
    special: "",
    brightness: 0.8,
  },
  {
    id: "anchor",
    title: "Anchored in Hope",
    description: "Steady heart, grounded soul.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Anchor.jpeg`,
    tags: ["Hope", "Faith", "Love"],
    price: 180,
    special: "",
  },
  {
    id: "big-tree",
    title: "Family Tree",
    description: "A story about growth and nature’s wisdom.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/BigTree.png`,
    tags: ["Family", "Nature", "Strength"],
    price: 500,
    special: "",
  },
  {
    id: "do-it",
    title: "DO IT",
    description: "An inspiring push toward action and courage.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/DOIT.jpeg`,
    tags: ["Strength", "Hope", "Art"],
    price: 250,
    special: "",
  },
  {
    id: "Eagles1",
    title: "Philadelphia Eagles",
    description: "Fly eagles fly.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Eagles.png`,
    tags: ["Sports", "Strength", "Freedom"],
    price: 250,
    special: "",
  },
  {
    id: "heart-pop-out",
    title: "Heart Pop Out",
    description: "Love bursting forth.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/HeartPopOut.png`,
    tags: ["Love", "Art", "Emotion"],
    price: 180,
    special: "",
  },
  {
    id: "heart-strap",
    title: "Happy Mother's Day",
    description: "The ties that bind us emotionally and physically.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/HeartStrap.png`,
    tags: ["Family", "Love", "Celebration"],
    price: 250,
    special: "",
    width: 2.5,
    coverAngle: 15,
  },
  {
    id: "jap-sword",
    title: "The Samurai",
    description: "A historical tale of honor and discipline.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/JapSword.png`,
    tags: ["Strength", "Art"],
    price: 250,
    special: "",
  },
  {
    id: "l",
    title: "Seagull",
    description: "Free spirit. Ocean eyes.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/L.png`,
    tags: ["Nature"],
    price: 250,
    special: "",
  },
  {
    id: "make-a-wish",
    title: "Make A Wish",
    description: "One breath. Endless dreams.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/MakeAWish.jpeg`,
    tags: ["Hope", "Faith"],
    price: 200,
    special: "",
  },
  {
    id: "many-hearts",
    title: "Many Hearts",
    description: "Exploring the diversity and unity of love.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/ManyHearts.png`,
    tags: ["Love", "Family"],
    price: 200,
    special: "",
  },
  {
    id: "puzzle-heart",
    title: "Puzzle Heart",
    description: "Love and life are a puzzle to be solved.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/PuzzleHeart.png`,
    tags: ["Love"],
    price: 200,
    special: "",
  },
  {
    id: "puzzle-heart-out",
    title: "Puzzle Heart II",
    description: "A piece of love scattered, waiting to be found.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/PuzzleHeartOut.png`,
    tags: ["Love", "Hope"],
    price: 200,
    special: "",
  },
  {
    id: "seahorse",
    title: "Seahorse",
    description: "A deep dive into the mysteries of the ocean.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Seahorse.png`,
    tags: ["Nature"],
    price: 250,
    special: "",
    width: 2.5,
    coverAngle: 15,
  },
  {
    id: "shell",
    title: "Sea Shell",
    description: "Listening to the echoes of the sea.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Shell.png`,
    tags: ["Nature", "Hope"],
    price: 250,
    special: "",
  },
  {
    id: "50th",
    title: "50th",
    description: "Cheers to half a century.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/50th.jpeg`,
    tags: ["Celebration", "Art"],
    x: 0,
    y: 0,
    price: 200,
    special: "",
    brightness: 1.2,
  },
  {
    id: "2024",
    title: "2024 Graduate",
    description: "Moments lived, memories kept.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/2024.jpeg`,
    tags: ["Celebration", "Hope"],
    x: 0,
    y: 0,
    price: 250,
    special: "Reduced",
    brightness: 1,
  },
  {
    id: "2024Grad",
    title: "2024 Graduate II",
    description: "Moments lived, memories kept.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/2024Grad.jpeg`,
    tags: ["Celebration", "Hope"],
    x: 0,
    y: 0,
    price: 200,
    special: "Reduced",
  },
  {
    id: "B",
    title: "Cincinnati Bengals",
    description: "Fierce spirit. Untamed pride.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/B.jpeg`,
    tags: ["Sports", "Strength"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
    brightness: 1.5,
  },
  {
    id: "Bull",
    title: "Houston Texans",
    description: "Tough as Texas soil.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Bull.jpeg`,
    tags: ["Sports", "Strength"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "BullCharge",
    title: "Buffalo Bills",
    description: "Never back down, always charging.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/BullCharge.jpeg`,
    tags: ["Sports", "Strength"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
    brightness: 1.5,
  },
  {
    id: "Candle",
    title: "Candle",
    description: "Warmth in the dark.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Candle.jpeg`,
    tags: ["Faith", "Hope"],
    x: 0,
    y: 0,
    price: 200,
    special: "",
    brightness: 1.2,
  },
  {
    id: "Candle2",
    title: "Candle II",
    description: "Warmth in the dark.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Candle2.jpeg`,
    tags: ["Faith", "Hope"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "Car",
    title: "Mercedes",
    description: "Precision meets luxury.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Car.png`,
    tags: ["Art"],
    x: 0,
    y: 0,
    price: 200,
    special: "",
    width: 4,
    coverAngle: 30,
  },
  {
    id: "Cheetah",
    title: "Cheetah",
    description: "Lightning speed, fierce spirit.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Cheetah.jpeg`,
    tags: ["Nature", "Strength"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "DallasStar",
    title: "Dallas Cowboys",
    description: "Driven by star power, fueled by tradition.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/DallasStar.jpeg`,
    tags: ["Sports", "Celebration"],
    x: 0,
    y: 0,
    price: 200,
    special: "",
  },
  {
    id: "Deer",
    title: "Deer",
    description: "Calm eyes, quiet presence.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Deer.jpeg`,
    tags: ["Nature", "Art"],
    x: 0,
    y: 0,
    price: 200,
    special: "",
  },
  {
  id: "DiamondHalf",
  title: "Yin Yang",
  description: "Precision meets harmony.",
  tags: ["Strength"],
  x: 0,
  y: 0,
  price: 200,
  special: "",
  width: 5,
  coverAngle: 40,
  imageUrl: `${process.env.PUBLIC_URL}/bookImages/DiamondHalf.png`,
  },
  {
    id: "Eagles2",
    title: "Philadelphia Eagles II",
    description: "Fly eagles fly.",
    tags: ["Sports"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Eagles.png`,
  },
  {
    id: "Eagles3",
    title: "Philadelphia Eagles III",
    description: "Fly eagles fly.",
    tags: ["Sports"],
    x: 0,
    y: 0,
    price: 300,
    special: "",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Eagles2.jpeg`,
  },
  {
    id: "EaglesStrip",
    title: "Philadelphia Eagles IV",
    description: "Fly eagles fly.",
    tags: ["Sports"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/EaglesStrip.jpeg`,
  },
  {
    id: "EaglesText",
    title: "Philadelphia Eagles V",
    description: "Fly eagles fly.",
    tags: ["Sports"],
    x: 0,
    y: 0,
    price: 300,
    special: "",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/EaglesText.jpeg`,
  },
  {
    id: "EaglesText2",
    title: "Philadelphia Eagles VI",
    description: "Fly eagles fly.",
    tags: ["Sports"],
    x: 0,
    y: 0,
    price: 350,
    special: "",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/EaglesText2.jpeg`,
  },
  {
    id: "Ellis",
    title: "Mr. & Mrs.",
    description: "Two hearts, one journey.",
    tags: ["Love", "Family", "Art"],
    x: 0,
    y: 0,
    price: 180,
    special: "",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Ellis.png`,
  },
  {
    id: "Glasses",
    title: "Glasses",
    description: "Clarity in every glance.",
    tags: ["Art"],
    x: 0,
    y: 0,
    price: 180,
    special: "",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Glasses.png`,
  },
  {
    id: "GSymbol",
    title: "Greenbay Packer",
    description: "Tradition forged in green and gold.",
    tags: ["Sports"],
    x: 0,
    y: 0,
    price: 300,
    special: "",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/GSymbol.jpeg`,
  },
  {
    id: "HeartGolden",
    title: "Popout Heart",
    description: "Love that stands out.",
    tags: ["Love"],
    x: 0,
    y: 0,
    price: 100,
    special: "",
    width: 2,
    coverAngle: 10,
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/HeartGolden.jpeg`,
  },
  {
    id: "HeartMult",
    title: "Heart Latte",
    description: "Warmth in every swirl.",
    tags: ["Love"],
    x: 0,
    y: 0,
    price: 200,
    special: "",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/HeartMult.jpeg`,
  },
  {
    id: "HomeSweet",
    title: "Home Sweet Home",
    description: "A home like no other.",
    tags: ["Celebration", "Family"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/HomeSweet.jpeg`,
  },
  {
    id: "Hope",
    title: "Pink Ribbon II",
    description: "Be stronger with you",
    tags: ["Hope"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Hope.jpeg`,
  },
  {
    id: "Horse",
    title: "Graceful Horse",
    description: "Strength in every gentle stride.",
    tags: ["Nature", "Strength"],
    x: 0,
    y: 0,
    price: 200,
    special: "",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Horse.jpeg`,
  },
  {
    id: "Jets",
    title: "Jets",
    description: "Speed and precision in flight.",
    tags: ["Sports"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
    brightness: 1.2,
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Jets.jpeg`,
  },
  {
    id: "KCHeart",
    title: "Kansas City Chiefs",
    description: "Heart of America.",
    tags: ["Sports", "Love"],
    x: 0,
    y: 0,
    price: 300,
    special: "",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/KCHeart.jpeg`,
  },
  {
    id: "Laugh",
    title: "Laugh",
    description: "Smile loud, live free.",
    tags: ["Art"],
    x: 0,
    y: 0,
    price: 200,
    special: "",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Laugh.png`,
  },
  {
    id: "Leaf",
    title: "Ying Yan Koi",
    description: "Pesilience, prost, and good fortune.",
    tags: ["Nature"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Leaf.jpeg`,
  },
  {
    id: "Lighthouse",
    title: "Lighthouse",
    description: "The guiding light.",
    tags: ["Art"],
    x: 0,
    y: 0,
    price: 180,
    special: "",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Lighthouse.jpeg`,
  },
  {
    id: "Love",
    title: "Love",
    description: "Heartbeats intertwined.",
    tags: ["Love"],
    x: 0,
    y: 0,
    price: 180,
    special: "",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Love.png`,
  },
  {
    id: "LoveButterfly",
    title: "Butterfly Hearts",
    description: "Love takes flight, delicate and free.",
    tags: ["Love", "Nature"],
    x: 0,
    y: 0,
    price: 300,
    special: "",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/LoveButterfly.jpeg`,
  },
  {
    id: "MerryChrist",
    title: "Merry Christmas",
    description: "Gifts and light fill the season.",
    tags: ["Celebration", "Faith"],
    x: 0,
    y: 0,
    price: 200,
    special: "",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/MerryChrist.jpeg`,
  },
  {
    id: "Mom",
    title: "Mom",
    description: "Heart of the family.",
    tags: ["Love", "Family"],
    x: 0,
    y: 0,
    price: 200,
    special: "",
    width: 2.5,
    coverAngle: 15,
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Mom.png`,
  },
  {
    id: "Mustache",
    title: "Mustache",
    description: "Style with a twist.",
    tags: ["Art"],
    x: 0,
    y: 0,
    price: 150,
    special: "",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Mustache.png`,
  },
  {
    id: "NY",
    title: "NY",
    description: "The city that never sleeps.",
    tags: ["Art"],
    x: 0,
    y: 0,
    price: 200,
    special: "",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/NY.png`,
  },
  {
    id: "NY2",
    title: "NY II",
    description: "The city that never sleeps.",
    tags: ["Art"],
    x: 0,
    y: 0,
    price: 200,
    special: "",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/NY2.jpeg`,
  },
  {
    id: "OpenBook",
    title: "Geometric",
    description: "Intricate layers revealing endless depth.",
    tags: ["Art"],
    x: 0,
    y: 0,
    price: 150,
    special: "reduced",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/OpenBook.png`,
  },
  {
    id: "PalmSunset",
    title: "Sunset Beach",
    description: "Where palms meet the fading light.",
    tags: ["Nature"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/PalmSunset.jpeg`,
  },
  {
    id: "Paw",
    title: "Paw",
    description: "A man's best friend.",
    tags: ["Nature", "Love"],
    x: 0,
    y: 0,
    price: 200,
    special: "",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Paw.png`,
  },
  {
    id: "Santa",
    title: "Santa",
    description: "The gift that keeps on giving.",
    tags: ["Celebration"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Santa.jpeg`,
  },
  {
    id: "StalkPlant",
    title: "Bamboo",
    description: "Strength in every stalk.",
    tags: ["Nature", "Strength"],
    x: 0,
    y: 0,
    price: 200,
    special: "",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/StalkPlant.jpeg`,
  },
  {
    id: "TrustGod",
    title: "Ask, Trust, and Thank God",
    description: "Ask with hope, trust in grace, thank with a grateful heart.",
    tags: ["Love", "Faith", "Hope", "Art"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/TrustGod.jpeg`,
  },
  {
    id: "USA",
    title: "USA",
    description: "The land of the free.",
    tags: ["Celebration"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/USA.jpeg`,
  },
  {
    id: "Vase",
    title: "Diamond",
    description: "A unique piece.",
    tags: ["Art"],
    x: 0,
    y: 0,
    price: 150,
    special: "",
    width: 3.8,
    coverAngle: 25,
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Vase.png`,
  },
  {
    id: "W",
    title: "Washington Commanders",
    description: "Hail to the Commanders.",
    tags: ["Sports"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/W.jpeg`,
  },
  {
    id: "WorldMap",
    title: "World Map",
    description: "The world at your fingertips.",
    tags: ["Art"],
    x: 0,
    y: 0,
    price: 300,
    special: "",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/WorldMap.jpeg`,
  },
  {
    id: "MrMrs II",
    title: "Mr. & Mrs. II",
    description: "Two hearts, one journey.",
    tags: ["Love", "Family", "Art"],
    x: 0,
    y: 0,
    price: 300,
    special: "",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/MrMs2.jpeg`,
    brightness: 0.9,
  },
  {
    id: "Lavender",
    title: "Lavender",
    description: "The world at your fingertips.",
    tags: ["Nature"],
    x: 0,
    y: 0,
    price: 300,
    special: "",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Lavender.jpeg`,
  },
];

export default booksData;