const booksData = [
  {
    id: "breast-cancer",
    title: "Pink Ribbon",
    description: "A captivating story about overcoming challenges.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/BreastCancer.png`,
    tags: ["Health", "Drama", "Inspiration"],
    x: 50,
    y: 50,
    price: 250,
    special: "",
  },
  {
    id: "child-of-god",
    title: "Child Of God",
    description: "An intriguing tale full of suspense and drama.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/ChildOfGod.png`,
    tags: ["Mystery", "Suspense", "Thriller"],
    price: 250,
    special: "",
  },
  {
    id: "anchor",
    title: "Anchor",
    description: "A symbolic tale of stability and strength.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Anchor.jpeg`,
    tags: ["Symbolism", "Stability", "Metaphor"],
    price: 250,
    special: "",
  },
  {
    id: "big-tree",
    title: "Family Tree",
    description: "A story about growth and nature’s wisdom.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/BigTree.png`,
    tags: ["Nature", "Growth", "Wisdom"],
    price: 250,
    special: "",
  },
  {
    id: "do-it",
    title: "DO IT",
    description: "An inspiring push toward action and courage.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/DOIT.jpeg`,
    tags: ["Motivation", "Action", "Courage"],
    price: 250,
    special: "",
  },
  {
    id: "eagles",
    title: "Eagles",
    description: "A soaring journey of freedom and vision.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Eagles.png`,
    tags: ["Freedom", "Vision", "Wildlife"],
    price: 250,
    special: "",
  },
  {
    id: "heart-pop-out",
    title: "Heart Pop Out",
    description: "Love bursting forth in a colorful display.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/HeartPopOut.png`,
    tags: ["Love", "Expression", "Emotion"],
    price: 250,
    special: "",
  },
  {
    id: "heart-strap",
    title: "Heart Strap",
    description: "The ties that bind us emotionally and physically.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/HeartStrap.png`,
    tags: ["Connection", "Love", "Emotion"],
    price: 250,
    special: "",
    width: 2.5,
    coverAngle: 15,
  },
  {
    id: "jap-sword",
    title: "Japanese Sword",
    description: "A historical tale of honor and discipline.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/JapSword.png`,
    tags: ["History", "Samurai", "Discipline"],
    price: 250,
    special: "",
  },
  {
    id: "l",
    title: "L",
    description: "A mysterious story surrounding a single letter.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/L.png`,
    tags: ["Mystery", "Alphabet", "Minimalism"],
    price: 250,
    special: "",
  },
  {
    id: "make-a-wish",
    title: "Make A Wish",
    description: "A heartfelt story about hope and dreams.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/MakeAWish.jpeg`,
    tags: ["Hope", "Dreams", "Inspiration"],
    price: 250,
    special: "",
  },
  {
    id: "many-hearts",
    title: "Many Hearts",
    description: "Exploring the diversity and unity of love.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/ManyHearts.png`,
    tags: ["Love", "Unity", "Diversity"],
    price: 250,
    special: "",
  },
  {
    id: "puzzle-heart",
    title: "Puzzle Heart",
    description: "Love and life are a puzzle to be solved.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/PuzzleHeart.png`,
    tags: ["Love", "Mystery", "Relationships"],
    price: 250,
    special: "",
  },
  {
    id: "puzzle-heart-out",
    title: "Puzzle Heart Out",
    description: "Pieces of love scattered, waiting to be found.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/PuzzleHeartOut.png`,
    tags: ["Heartbreak", "Healing", "Discovery"],
    price: 250,
    special: "",
  },
  {
    id: "seahorse",
    title: "Seahorse",
    description: "A deep dive into the mysteries of the ocean.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Seahorse.png`,
    tags: ["Ocean", "Mystery", "Wildlife"],
    price: 250,
    special: "",
    width: 2.5,
    coverAngle: 15,
  },
  {
    id: "shell",
    title: "Shell",
    description: "Listening to the echoes of the sea.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Shell.png`,
    tags: ["Nature", "Peace", "Reflection"],
    price: 250,
    special: "",
  },
  {
    id: "50th",
    title: "50th",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/50th.jpeg`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "2024",
    title: "2024",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/2024.jpeg`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "2024Grad",
    title: "2024grad",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/2024Grad.jpeg`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "B",
    title: "B",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/B.jpeg`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "Bull",
    title: "Bull",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Bull.jpeg`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "BullCharge",
    title: "Bullcharge",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/BullCharge.jpeg`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "Candle",
    title: "Candle",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Candle.jpeg`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "Candle2",
    title: "Candle2",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Candle2.jpeg`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "Car",
    title: "Car",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Car.png`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "Cheetah",
    title: "Cheetah",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Cheetah.jpeg`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "DallasStar",
    title: "Dallasstar",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/DallasStar.jpeg`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "Deer",
    title: "Deer",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Deer.jpeg`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "DiamondHalf",
    title: "Diamondhalf",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/DiamondHalf.png`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "Eagles",
    title: "Eagles",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Eagles.jpeg`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "Eagles2",
    title: "Eagles2",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Eagles2.jpeg`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "EaglesStrip",
    title: "Eaglesstrip",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/EaglesStrip.jpeg`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "EaglesText",
    title: "Eaglestext",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/EaglesText.jpeg`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "EaglesText2",
    title: "Eaglestext2",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/EaglesText2.jpeg`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "Ellis",
    title: "Ellis",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Ellis.png`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "Glasses",
    title: "Glasses",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Glasses.png`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "GSymbol",
    title: "Gsymbol",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/GSymbol.jpeg`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "HeartGolden",
    title: "Heartgolden",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/HeartGolden.jpeg`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "HeartMult",
    title: "Heartmult",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/HeartMult.jpeg`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "HomeSweet",
    title: "Homesweet",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/HomeSweet.jpeg`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "Hope",
    title: "Hope",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Hope.jpeg`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "Horse",
    title: "Horse",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Horse.jpeg`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "Jets",
    title: "Jets",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Jets.jpeg`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "KCHeart",
    title: "Kcheart",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/KCHeart.jpeg`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "Laugh",
    title: "Laugh",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Laugh.png`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "Leaf",
    title: "Leaf",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Leaf.jpeg`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "Lighthouse",
    title: "Lighthouse",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Lighthouse.jpeg`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "Love",
    title: "Love",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Love.png`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "LoveButterfly",
    title: "Lovebutterfly",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/LoveButterfly.jpeg`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "MerryChrist",
    title: "Merrychrist",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/MerryChrist.jpeg`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "Mom",
    title: "Mom",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Mom.png`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "Mustache",
    title: "Mustache",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Mustache.png`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "NY",
    title: "Ny",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/NY.png`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "NY2",
    title: "Ny2",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/NY2.jpeg`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "OpenBook",
    title: "Openbook",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/OpenBook.png`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "PalmSunset",
    title: "Palmsunset",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/PalmSunset.jpeg`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "Paw",
    title: "Paw",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Paw.png`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "Santa",
    title: "Santa",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Santa.jpeg`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "StalkPlant",
    title: "Stalkplant",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/StalkPlant.jpeg`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "TrustGod",
    title: "Trustgod",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/TrustGod.jpeg`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "USA",
    title: "Usa",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/USA.jpeg`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "Vase",
    title: "Vase",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/Vase.png`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "W",
    title: "W",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/W.jpeg`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
  {
    id: "WorldMap",
    title: "Worldmap",
    description: "A unique piece of digital artwork.",
    imageUrl: `${process.env.PUBLIC_URL}/bookImages/WorldMap.jpeg`,
    tags: ["Art", "Gallery"],
    x: 0,
    y: 0,
    price: 250,
    special: "",
  },
];

export default booksData;
